---
- name: Yaml Playbook to fetch the App module version deployed on each server
  hosts: DIT                                                       # this is the server group for which we want to execute this playbook
  gather_facts: True                                               # we want to gater facts about the remote systems so we can use them
  ignore_errors: False                                             # Generally playbooks will stop executing any more steps on a host that has a task fail. Sometimes, though, you want to continue on. To do so, we use this


  roles:
    - role : src_node_fetch                                               # Invoking node_fetch role to be executed with below variables only if when condition is true
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/   # Setting the application variable here only if when condition is true
      EnvName: dit2                                                   # Setting the environment name variable here only if when condition is true
      when: ansible_hostname    == 'machine1' and src_node == "dit2"              



    - role : src_node_fetch                                               # Invoking node_fetch role to be executed with below variables only if when condition is true
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/   # Setting the application variable here only if when condition is true
      EnvName: dit1                                                   # Setting the environment name variable here only if when condition is true
      when: ansible_hostname    == 'machine1' and src_node == "dit1"






    - role : dest_node_fetch                                                     
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/   # Setting the application variable here only if when condition is true
      EnvName: dit1                                                   # Setting the environment name variable here only if when condition is true
      when: ansible_hostname    == 'machine1' and dest_node == "dit1"
      run_once: true

    - role : dest_node_fetch
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/   # Setting the application variable here only if when condition is true
      EnvName: dit2                                                   # Setting the environment name variable here only if when condition is true
      when: ansible_hostname    == 'machine1' and dest_node == "dit2"
      run_once: true





  tasks:
    - name: print source
      debug:
        msg: "{{ src_dict }}"
      run_once: true

    - name: print dest
      debug:
        msg: "{{ dest_dict }}"
      run_once: true

    - name: calling python module manually created
      dictinary_compare: 
        src: "{{ src_dict  }}"
        dest: "{{  dest_dict }}" 
      delegate_to: 127.0.0.1
      run_once: true
      register: data1
    - name: debug1
      debug:
        msg: "{{ data1 }}"
      delegate_to: 127.0.0.1
      run_once: true

...
