---                                                                                                           # From here we are starting the playbook three "---" denotes a yml start.
 - name: Checking the Variable Values                                                                         # this is just giving the task tag
   debug:                                                                                                     # debug task invoked
     msg: " {{ EnvName }} {{ AppPath }} "                                                                     # printing the Variables Supplied to this role from main playbook.


 - name: Find command to search .MF files and store the file names in find_Output register                    # task brief headline
   shell: "find -name *.MF"                                                                                   
   args:
     chdir: "{{ AppPath }}"                                                                                   # Argument is the path in which we want to search these *.MF files
   register: find_output                                                                                      



 - name: Read the find_Output register file names and store their data  to report_out                         # task brief headline
   shell: cat {{ AppPath }}/{{ item }} | egrep 'Module-Name|Built-Version'                                    
   with_items:                                                                                                # trigger to loop
     - "{{ find_output.stdout_lines }}"                                                                       
   register: report_out                                                                                       # register all the stdout of the cat command


 - name: Make a single file for each environmonet for all the deployed modules and version in txt format      # task brief headline
   shell: echo  "{{ item.stdout }}"      |  tr -d $'\r'|cut -d':' -f2 | paste -d':' - -|sed "s| ||g"                                          
   delegate_to: localhost                                                                                     # making sure we are stroing the files on local system
   with_items:                                                                                                # trigger to loop
     - "{{ report_out.results }}"                                                                             # execute loop for each results stored in  last step
   register: execution_of_shell

 - name: echo data
   debug:
     msg: "{{ EnvName }} , {{ item.stdout }}"
   with_items:                                                                                                # trigger to loop
     - "{{ execution_of_shell.results }}"

 - name: set facts 
   set_fact:
           module_output: "{{ module_output|default([]) + [ {EnvName : item.stdout } ] }}"
   with_items:                                                                                                # trigger to loop
     - "{{ execution_of_shell.results }}"
 - name: echo
   debug:
     msg: "{{ module_output }}"



