---

 - name: Find command to search .MF files and store the file names in find_Output register                    # task brief headline
   shell: |
          find {{ AppPath }} -name "*.MF" -exec cat {} \;|egrep 'Module-Name|Built-Version' |tr -d $'\r'|cut -d':' -f2 | paste -d',' - -|sed "s| ||g"|sort| uniq|sed "s|^|'|g"|sed "s|,|': '|g"|sed "s|$|',|g"|tr '\n' ' '|sed "s|^|{ |g"|sed "s|, $|}|g"
   register: find_output_1

 - name: creating output
   shell: |
          echo "{{ find_output_1.stdout }}" >./src_node_fetch/vars/main.yml
   delegate_to: localhost


         


